gradle:
  image: gradle:alpine
  working_dir: /home/gradle/project
  volumes:
    - ./:/home/gradle/project
    - ~/.m2:/home/gradle/.m2
    - ~/.gradle:/home/gradle/.gradle
front:
  container_name: front
  image: node:12
  working_dir: /home/node/app
  volumes:
    - "./:/home/node/app"
  command: npm start
  ports:
    - "8080:8080"
account:
  container_name: account
  image: openjdk:8
  working_dir: /usr/src
  command: java -jar /usr/src/account-fat.jar -conf /usr/src/account.json -cluster
  environment:
    - "JAVA_TOOL_OPTIONS=\"-agentlib:jdwp=transport=dt_socket,address=8001,server=y,suspend=n\""
  ports:
    - "3001:3001"
    - "8001:8001"
  volumes:
    - "./account/build/libs/account-fat.jar:/usr/src/account-fat.jar"
    - "./conf/account.json:/usr/src/account.json"
    - "./conf/default-cluster.xml:/usr/src/cluster.xml"
  links:
    - postgres
    - redis
portal:
  container_name: portal
  image: openjdk:alpine
  working_dir: /usr/src
  command: java -jar /usr/src/portal-fat.jar -conf /usr/src/portal.json -cluster
  environment:
    - "JAVA_TOOL_OPTIONS=\"-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n\""
  ports:
    - "3000:3000"
    - "8000:8000"
  volumes:
    - "./portal/build/libs/portal-fat.jar:/usr/src/portal-fat.jar"
    - "./conf/portal.json:/usr/src/portal.json"
    - "./conf/default-cluster.xml:/usr/src/cluster.xml"
  links:
    - postgres
    - redis
project:
  container_name: project
  image: openjdk:alpine
  working_dir: /usr/src
  command: java -jar /usr/src/project-fat.jar -conf /usr/src/project.json -cluster
  environment:
    - "JAVA_TOOL_OPTIONS=\"-agentlib:jdwp=transport=dt_socket,address=8002,server=y,suspend=n\""
  ports:
    - "3002:3002"
    - "8002:8002"
  volumes:
    - "./project/build/libs/project-fat.jar:/usr/src/project-fat.jar"
    - "./conf/project.json:/usr/src/project.json"
    - "./conf/default-cluster.xml:/usr/src/cluster.xml"
  links:
    - postgres
    - redis
kanban:
  container_name: kanban
  image: openjdk:alpine
  working_dir: /usr/src
  command: java -jar /usr/src/kanban-fat.jar -conf /usr/src/kanban.json -cluster
  environment:
    - "JAVA_TOOL_OPTIONS=\"-agentlib:jdwp=transport=dt_socket,address=8003,server=y,suspend=n\""
  ports:
    - "3003:3003"
    - "8003:8003"
  volumes:
    - "./kanban/build/libs/kanban-fat.jar:/usr/src/kanban-fat.jar"
    - "./conf/kanban.json:/usr/src/kanban.json"
    - "./conf/default-cluster.xml:/usr/src/cluster.xml"
  links:
    - postgres
    - redis
postgres:
  container_name: postgres
  image: postgres:9.6
  environment:
    POSTGRES_USER: kyra
    POSTGRES_PASSWORD: kyra_1234
    POSTGRES_DB: kyra
  volumes:
    - /home/dev/DEV/pg_data:/var/lib/postgresql/data
  ports:
    - "5432:5432"
redis:
  container_name: redis
  image: redis:5.0
  ports:
    - "6379:6379"
nginx:
  container_name: nginx
  image: nginx:latest
  ports:
    - "80:80"
  links:
    - front
    - account
    - portal
    - project
    - kanban
  volumes:
    - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
