gradle:
  image: gradle:alpine
  working_dir: /home/gradle/project
  volumes:
    - ./:/home/gradle/project
    - ~/.m2:/home/gradle/.m2
    - ~/.gradle:/home/gradle/.gradle
authentication:
  container_name: authentication
  image: openjdk:8
  working_dir: /usr/src
  command: java -jar /usr/src/authentication-fat.jar -conf /usr/src/authentication.json
  environment:
    - "JAVA_TOOL_OPTIONS=\"-agentlib:jdwp=transport=dt_socket,address=8001,server=y,suspend=n\""
  ports:
    - "3001:3001"
    - "8001:8001"
  volumes:
    - "./authentication/build/libs/authentication-fat.jar:/usr/src/authentication-fat.jar"
    - "./conf/authentication.json:/usr/src/authentication.json"
  links:
    - postgres
    - redis
portal:
  container_name: portal
  image: openjdk:alpine
  working_dir: /usr/src
  command: java -jar /usr/src/portal-fat.jar -conf /usr/src/portal.json
  environment:
    - "JAVA_TOOL_OPTIONS=\"-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n\""
  ports:
    - "3000:3000"
    - "8000:8000"
  volumes:
    - "./portal/build/libs/portal-fat.jar:/usr/src/portal-fat.jar"
    - "./conf/portal.json:/usr/src/portal.json"
  links:
    - postgres
    - redis
postgres:
  container_name: postgres
  image: postgres:9.6
  environment:
    POSTGRES_USER: kyra
    POSTGRES_PASSWORD: kyra_1234
    POSTGRES_DB: kyra
  volumes:
    - /home/dev/DEV/pg_data:/var/lib/postgresql/data
  ports:
    - "5432:5432"
redis:
  container_name: redis
  image: redis:5.0
  ports:
    - "6379:6379"
nginx:
  container_name: nginx
  image: nginx:latest
  ports:
    - "80:80"
  links:
    - authentication
    - portal
  volumes:
    - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
